linebubble<-read.table("BUBBLESORT-PLOTLINE.txt",header=TRUE,sep="")
lineheap<-read.table("HEAPSORT-PLOTLINE.txt",header=TRUE,sep="")
linebubble<-as.matrix(linebubble)
lineheap<-as.matrix(lineheap)
plot(linebubble[,1],linebubble[,2],type="l",main="Gráfico de curva - Bubblesort",xlab="Elementos no array",ylab="Comparações",col="blue")
lines(linebubble[,1],linebubble[,3],col="red",type="l")
lines(linebubble[,1],linebubble[,4],col="green",type="l")
legend("topleft",c("Crescente","Decrescente","Aleatório"),col=c("blue","red","green"),lty=1,lwd=2,bty="n")
plot(lineheap[,1],lineheap[,2],type="l",main="Gráfico de curva - Heapsort",xlab="Elementos no array",ylab="Comparações",col="blue")
lines(lineheap[,1],lineheap[,3],col="red",type="l")
lines(lineheap[,1],lineheap[,4],col="green",type="l")
legend("topleft",c("Crescente","Decrescente","Aleatório"),col=c("blue","red","green"),lty=1,lwd=2,bty="n")
plot(linebubble[,1],linebubble[,4],type="l",main="BUBBLESORT VS HEAPSORT - ALEATÓRIO",xlab="Elementos no array",ylab="Comparações",col="blue")
lines(lineheap[,1],lineheap[,4],col="green",type="l")
legend("topleft",c("Bubblesort","Heapsort"),col=c("blue","green"),lty=1,lwd=2,bty="n")
plot(linebubble[,1],linebubble[,3],type="l",main="BUBBLESORT VS HEAPSORT - DECRESCENTE",xlab="N° de elementos no array",ylab="Comparações",col="blue")
lines(lineheap[,1],lineheap[,3],col="green",type="l")
legend("topleft",c("Bubblesort","Heapsort"),col=c("blue","green"),lty=1,lwd=2,bty="n")
